/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	20160717
#define KERNEL_VERSION_BUILD_HEX	0x0
#define KERNEL_VERSION_BUILD_STR	"20160717-AChoir50"
#define KERNEL_VERSION_BUILD_RC	"20160717-AChoir50\0"
#define KERNEL_RELEASE_RC	"0.4\0"
#define KERNEL_RELEASE_STR	"0.4"
#define KERNEL_VERSION_RC	"0.4\0"
#define KERNEL_VERSION_STR	"0.4"
#define REACTOS_DLL_VERSION_MAJOR	42
#define REACTOS_DLL_RELEASE_RC	"42.4\0"
#define REACTOS_DLL_RELEASE_STR	"42.4"
#define REACTOS_DLL_VERSION_RC	"42.4\0"
#define REACTOS_DLL_VERSION_STR	"42.4"
#endif
/* EOF */
